### ISSUE TITLE
Assigning score to one team but not the other

### ISSUE THREAD

**Issue by iAmGiG** [tadams0/DebateSchedulerFinal#5] opened 2016-11-17 01:45 UTC
If you were to assign score to one team on a 2 week, 2 team season but not to the other team. then you click Update score a "null reference exception" is thrown in Referee.aspx.cs 
![image](https://cloud.githubusercontent.com/assets/22671190/20373052/7c880c0e-ac3d-11e6-99af-53e0464f9a4b.png)
![error on site](https://cloud.githubusercontent.com/assets/22671190/20373072/9de70ce2-ac3d-11e6-9117-ee6b6aee7f96.png)

**Comment by ProgenitorG** [comment] 2016-11-17 01:48
That should be only a null exception if you aren't logged in. Have you synced recently?

**Comment by ProgenitorG** [comment] 2016-11-17 01:52
![11162016snip](https://cloud.githubusercontent.com/assets/17413330/20373195/98c976ea-ac3e-11e6-9d6d-49da9f355419.JPG)
This is what happens for me.

**Comment by tadams0** [comment] 2016-11-17 01:55
Although I was unable to reproduce the issue 
![false](https://cloud.githubusercontent.com/assets/22671422/20373252/f1b411a2-ac3e-11e6-87f6-e8ebb186869f.png) , thanks to the screenshots it's fairly obvious what is going on, so I surrounded the logic for the update button in a check ensuring the logged in user exists before executing code. This was fixed in [this commit.](https://github.com/tadams0/DebateSchedulerFinal/commit/c929cb840a33f21e8072cb1749c5c62261c15cfb)

**Closed as completed by tadams0** 2016-11-17 01:55 UTC
